name: Daily Travel Advisory Update

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 AM UTC
  workflow_dispatch:  # Allows manual runs if needed

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run Python Script
        run: python Canada-Script.py

      - name: List Files in Current Directory
        run: ls -al

      - name: Verify CSV File Exists
        run: |
          if [ -f "travel_advisories.csv" ]; then
            echo "File exists!"
          else
            echo "File does not exist!"
            exit 1
          fi

      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add travel_advisories.csv
          git commit -m "Daily data update"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/pingmaestro/Travel-Advisory.git HEAD:main
